version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  flask :
    build: ~/career-flask-server
    container_name: flask-keyog-dev
    restart : always
    ports :
      - "8888:8888"
    volumes :
      - ~/career-flask-server:/opt
    environment:
      TZ: "Asia/Seoul"