"""empty message

Revision ID: b2116859f149
Revises: ddcce1d0216d
Create Date: 2021-04-09 15:15:01.426596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2116859f149'
down_revision = 'ddcce1d0216d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('skills_sector_ibfk_2', 'skills_sector', type_='foreignkey')
    op.drop_constraint('skills_sector_ibfk_1', 'skills_sector', type_='foreignkey')
    op.create_foreign_key(None, 'skills_sector', 'jobskill', ['job_skill_id'], ['id'])
    op.create_foreign_key(None, 'skills_sector', 'jobsector', ['job_sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills_sector', type_='foreignkey')
    op.drop_constraint(None, 'skills_sector', type_='foreignkey')
    op.create_foreign_key('skills_sector_ibfk_1', 'skills_sector', 'jobsector', ['job_skill_id'], ['id'])
    op.create_foreign_key('skills_sector_ibfk_2', 'skills_sector', 'jobskill', ['job_sector_id'], ['id'])
    # ### end Alembic commands ###
