"""empty message

Revision ID: ddcce1d0216d
Revises: 19ec7aa93c32
Create Date: 2021-04-01 00:55:50.007299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddcce1d0216d'
down_revision = '19ec7aa93c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('main_flag', sa.Boolean(), nullable=False))
    op.add_column('resume', sa.Column('user_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'resume', 'user', ['user_id'], ['id'])
    op.drop_column('resume', 'main_resume')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'main_resume_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('main_resume_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'resume', ['main_resume_id'], ['id'])
    op.add_column('resume', sa.Column('main_resume', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'user_id')
    op.drop_column('resume', 'main_flag')
    # ### end Alembic commands ###
